[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer = true
optimizer_runs = 200
gas_limit = 100000000000000000


[rpc_endpoints]
mainnet = "https://nameless-withered-spring.matic.quiknode.pro/7915e63a146cf8b4e372c88d2a372a21edb2d7e3/"
