[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 200
optimizer = true
optimizer_runs = 200
[rpc_endpoints]
mainnet = "${MAINNET_RPC_ENDPOINT}"

[rpc_endpoints]
mainnet = "${MAINNET}"

# See more config options https://github.com/gakonst/foundry/tree/master/config