[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 100
optimizer = true
optimizer_runs = 200


[rpc_endpoints]
mainnet = "https://nameless-withered-spring.matic.quiknode.pro/7915e63a146cf8b4e372c88d2a372a21edb2d7e3/"
goerli = "https://eth-goerli.g.alchemy.com/v2/KCU0kYzUrii2zqakHBksCGTz8s8JO6re"
