[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
script= 'scripts'
fuzz_runs = 200
optimizer = true
cache_path = 'cache'
cache=true
optimizer_runs = 200
include_paths = ['src/test', 'src/utils', 'src/interfaces']
# See more config options https://github.com/gakonst/foundry/tree/master/config