[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
scripts= 'scripts'
fuzz_runs = 250
optimizer = true
optimizer_runs = 200
include_paths = ['src/test', 'src/utils', 'src/interfaces']
# See more config options https://github.com/gakonst/foundry/tree/master/config