name: test

on: [push, pull_request]

jobs:
  check:
    name: LimitOrders-v0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install eth-abi
        run: pip3 install eth-abi

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv -f${{ secrets.MAINNET_ENDPOINT }} --fork-block-number 15233771 --ffi

      - name: Run snapshot
        run: forge snapshot -vvv -f${{ secrets.MAINNET_ENDPOINT }} --fork-block-number 15233771 --ffi
